[package]
name = "rustcord"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.10"
rfd = "0.12"
ashpd = "0.10"
pipewire = "0.5"
ffmpeg-next = "4.3"
tokio = { version = "1.27", features = ["rt-multi-thread", "macros"] }
eframe = "0.27"
egui = "0.27"
anyhow = "1.0"
bindgen = "0.51"

[[bin]]
name = "rustcord"
path = "src/main.rs"
