[package]
name = "rustcord"
version = "0.1.0"
edition = "2021"

[dependencies]
scrap = "0.5.0"
opencv = "0.94.3"
gstreamer = "0.20"
gstreamer-app = "0.20"
image = "0.24"
anyhow = "1.0"
crossbeam = "0.8"
eframe = "0.22"
egui = "0.22"
bytemuck_derive = "1.9.2"

[[bin]]
name = "rustcord"
path = "src/main.rs"
